-- INSERT INTO Idioma (codIdioma, nombre) VALUES
-- (1, 'Español'),
-- (2, 'Inglés'),
-- (3, 'Francés'),
-- (4, 'Alemán'),
-- (5, 'Italiano'),
-- (6, 'Portugués'),
-- (7, 'Chino'),
-- (8, 'Japonés'),
-- (9, 'Coreano'),
-- (10, 'Ruso');

INSERT INTO Sector (codSector, nombre) VALUES
(1, 'Compras'),
(2, 'Ventas'),
(3, 'Recursos Humanos');

INSERT INTO Departamento (nombre, codSector) VALUES
('Contabilidad', 3),
('Marketing', 2),
('Logística', 1),
('Capacitación', 3),
('Selección', 3),
('Relaciones Laborales', 3),
('Salud Ocupacional', 3),
('Seguridad e Higiene', 3);

INSERT INTO Pais (codPais, nombre) VALUES
('ARG', 'Argentina'),
('BRA', 'Brasil'),
('CHI', 'Chile'),
('URU', 'Uruguay'),
('PAR', 'Paraguay'),
('BOL', 'Bolivia'),
('PER', 'Perú');

INSERT INTO Provincia (nombre, codPais) VALUES
('Buenos Aires', 'ARG'),
('Córdoba', 'ARG'),
('Santa Fe', 'ARG'),
('Mendoza', 'ARG'),
('Santiago del Estero', 'ARG'),
('Chubut', 'ARG')
('Tucumán', 'ARG'),
('Salta', 'ARG'),
('Jujuy', 'ARG'),
('Chaco', 'ARG'),
('Formosa', 'ARG'),
('Misiones', 'ARG'),
('Corrientes', 'ARG'),
('Entre Ríos', 'ARG'),
('La Pampa', 'ARG'),
('San Juan', 'ARG'),
('San Luis', 'ARG'),
('La Rioja', 'ARG'),
('Catamarca', 'ARG'),
('Neuquén', 'ARG'),
('Río Negro', 'ARG'),
('Santiago', 'CHI'),
('Valparaíso', 'CHI'),
('Concepción', 'CHI'),
('Antofagasta', 'CHI'),
('Valdivia', 'CHI'),
('São Paulo', 'BRA'),
('Rio de Janeiro', 'BRA'),
('Salvador', 'BRA'),
('Brasília', 'BRA'),
('Fortaleza', 'BRA'),
('Montevideo', 'URU'),
('Canelones', 'URU'),
('Maldonado', 'URU'),
('Rocha', 'URU'),
('Colonia', 'URU'),
('Asunción', 'PAR'),
('Ciudad del Este', 'PAR'),
('Encarnación', 'PAR'),
('Luque', 'PAR'),
('San Lorenzo', 'PAR'),
('La Paz', 'BOL'),
('Santa Cruz', 'BOL'),
('Cochabamba', 'BOL'),
('Sucre', 'BOL'),
('Oruro', 'BOL'),
('Lima', 'PER'),
('Arequipa', 'PER'),
('Trujillo', 'PER'),
('Cusco', 'PER'),
('Chiclayo', 'PER');


INSERT INTO Localidad (nombre, codProv) VALUES
('San Miguel de Tucumán', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Yerba Buena', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Tafí Viejo', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Banda del Río Salí', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Alderetes', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Famaillá', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Aguilares', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Concepción', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Monteros', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Río Seco', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Simoca', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Lules', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Tafí del Valle', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Trancas', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Burruyacú', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Graneros', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('La Cocha', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Leales', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Chicligasta', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Alberdi', (SELECT codProv FROM Provincia WHERE nombre = 'Tucumán')),
('Salta', (SELECT codProv FROM Provincia WHERE nombre = 'Salta')),
('Cafayate', (SELECT codProv FROM Provincia WHERE nombre = 'Salta')),
('San Antonio de los Cobres', (SELECT codProv FROM Provincia WHERE nombre = 'Salta')),
('Santiago del Estero', (SELECT codProv FROM Provincia WHERE nombre = 'Santiago del Estero')),
('La Banda', (SELECT codProv FROM Provincia WHERE nombre = 'Santiago del Estero')),
('Termas de Río Hondo', (SELECT codProv FROM Provincia WHERE nombre = 'Santiago del Estero')),
('Buenos Aires', (SELECT codProv FROM Provincia WHERE nombre = 'Buenos Aires')),
('La Plata', (SELECT codProv FROM Provincia WHERE nombre = 'Buenos Aires')),
('Mar del Plata', (SELECT codProv FROM Provincia WHERE nombre = 'Buenos Aires')),
('Comodoro Rivadavia', (SELECT codProv FROM Provincia WHERE nombre = 'Chubut')),
('Puerto Madryn', (SELECT codProv FROM Provincia WHERE nombre = 'Chubut')),
('Esquel', (SELECT codProv FROM Provincia WHERE nombre = 'Chubut')),
('San Salvador de Jujuy', (SELECT codProv FROM Provincia WHERE nombre = 'Jujuy')),
('Humahuaca', (SELECT codProv FROM Provincia WHERE nombre = 'Jujuy')),
('Tilcara', (SELECT codProv FROM Provincia WHERE nombre = 'Jujuy'));